import type { Customer, CustomerAddress, CustomerLookup, CustomerOrder } from '@/entities/customer/model/types';

export type CustomerDto = { id: number; name?: string; phone?: string; registered_at?: string | null; email?: string | null; active?: boolean; spam?: boolean; orders_count?: number; orders_sum?: number };
export type AddressDto = { id: number; customer_id: number; city_id: number; city_name?: string; street_id: number; street?: string; home?: string; apartment?: string; entrance?: string; floor?: string; dom_true?: boolean; comment?: string; is_main?: boolean; xy?: string; delivery?: { point_id?: number; sum_div?: number; free_drive?: boolean; pay_active?: boolean } };
export type OrderDto = { order_id: number; point_id: number; point_name?: string; date_time?: string; is_preorder?: boolean; sum?: number; type: number; type_label?: string; status: number; status_label?: string; time_to_client?: string | null; steps?: Array<{ name?: string; active?: number }> };
export type LookupDto = { phone?: string; registered?: boolean; customer?: CustomerDto | null; last_order?: { order_id: number; city_id: number; point_id?: number | null; date?: string | null; time?: string | null; sum?: number; type_order: number } | null; last_order_state?: string; addresses?: AddressDto[] };

export function mapCustomer(value: CustomerDto): Customer { return { id: Number(value.id), name: String(value.name ?? ''), phone: String(value.phone ?? ''), registeredAt: value.registered_at ?? null, email: value.email ?? null, active: Boolean(value.active), spam: Boolean(value.spam), ordersCount: Number(value.orders_count ?? 0), ordersSum: Number(value.orders_sum ?? 0) }; }
export function mapAddress(value: AddressDto): CustomerAddress { return { id: Number(value.id), customerId: Number(value.customer_id), cityId: Number(value.city_id), cityName: String(value.city_name ?? ''), streetId: Number(value.street_id), street: String(value.street ?? ''), home: String(value.home ?? ''), apartment: String(value.apartment ?? ''), entrance: String(value.entrance ?? ''), floor: String(value.floor ?? ''), domTrue: Boolean(value.dom_true), comment: String(value.comment ?? ''), isMain: Boolean(value.is_main), xy: String(value.xy ?? ''), delivery: { pointId: Number(value.delivery?.point_id ?? 0), sumDiv: Number(value.delivery?.sum_div ?? 0), freeDrive: Boolean(value.delivery?.free_drive), payActive: Boolean(value.delivery?.pay_active) } }; }
export function mapOrder(value: OrderDto): CustomerOrder { return { orderId: Number(value.order_id), pointId: Number(value.point_id), pointName: String(value.point_name ?? ''), dateTime: String(value.date_time ?? ''), isPreorder: Boolean(value.is_preorder), sum: Number(value.sum ?? 0), type: Number(value.type), typeLabel: String(value.type_label ?? ''), status: Number(value.status), statusLabel: String(value.status_label ?? ''), timeToClient: value.time_to_client ?? null, steps: (value.steps ?? []).map((step) => ({ name: String(step.name ?? ''), active: Number(step.active ?? 0) })) }; }
export function mapLookup(value: LookupDto): CustomerLookup { const order = value.last_order; return { phone: String(value.phone ?? ''), registered: Boolean(value.registered), customer: value.customer ? mapCustomer(value.customer) : null, lastOrder: order ? { orderId: Number(order.order_id), cityId: Number(order.city_id), pointId: order.point_id == null ? null : Number(order.point_id), date: order.date ?? null, time: order.time ?? null, sum: Number(order.sum ?? 0), typeOrder: Number(order.type_order) } : null, lastOrderState: String(value.last_order_state ?? ''), addresses: (value.addresses ?? []).map(mapAddress) }; }
