import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { AuthProvider } from "@/features/auth/ui/AuthProvider/AuthProvider";
import { QueryProvider } from "@/shared/api/QueryProvider";
import { NotificationHost } from "@/widgets/notification/ui/NotificationHost/NotificationHost";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["cyrillic"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Жако",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body 
        className={`${roboto.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            {children}
            <NotificationHost />
          </AuthProvider>
        </QueryProvider>
        {process.env.NEXT_PUBLIC_YMAPS_API_KEY ? (
          <Script
            src={`https://api-maps.yandex.ru/v3/?apikey=${process.env.NEXT_PUBLIC_YMAPS_API_KEY}&lang=ru_RU`}
            strategy="beforeInteractive"
            data-ymaps3="true"
          />
        ) : null}
      </body>
    </html>
  );
}
